# This file only contains rules that differ from the rubocop defaults.
#

# Style

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Style/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false 

Style/Encoding:
  EnforcedStyle: when_needed
  SupportedStyles:
    - when_needed
    - always

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent
  SupportedStyles:
    - special_inside_parenthese
    - consistent

Style/Next:
  Enabled: false

Style/PredicateName:
  NamePrefixBlacklist: []

Style/SignalException:
  EnforcedStyle: only_raise
  SupportedStyles:
    - only_raise
    - only_fail
    - semantic

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space
  SupportedStyles:
    - space
    - no_space

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  SupportedStyles:
    - comma
    - no_comma

# Metrics

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to ~120 characters.'
  Max: 125
  AllowURI: true

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Lint

Lint/UnusedMethodArgument:
  Enabled: false
